// Simple PDF Engine mapping logic to wrap HTML template into a printable document

export function renderPDF(templateHtml: string, dataParams: Record<string, any>): string {
    let replacedHtml = templateHtml || '';

    // Replace all instances of {{key}} with config data.
    Object.keys(dataParams).forEach(key => {
        const regex = new RegExp(`{{${key}}}`, 'g');
        replacedHtml = replacedHtml.replace(regex, dataParams[key] || '');
    });

    // We generate a full standalone HTML shell that triggers print or PDF generation natively
    const htmlShell = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Invoice - ${dataParams.targetName || 'Document'}</title>
        <style>
            @page { size: A4; margin: 20mm; }
            body { 
                font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; 
                color: #333; 
                line-height: 1.6;
                margin: 0;
                padding: 0;
            }
            .document-container {
                max-width: 800px;
                margin: 0 auto;
            }
            h1, h2, h3 { color: #1e293b; }
            table { width: 100%; border-collapse: collapse; margin: 20px 0; }
            th, td { padding: 12px; border-bottom: 1px solid #e2e8f0; text-align: left; }
            th { background-color: #f8fafc; font-weight: bold; }
            .total-row { font-weight: bold; background-color: #f1f5f9; }
            
            /* Print Specific */
            @media print {
                body { print-color-adjust: exact; -webkit-print-color-adjust: exact; }
                .no-print { display: none; }
            }
        </style>
    </head>
    <body>
        <div class="no-print" style="background:#1e293b; color:white; padding: 12px 20px; display: flex; justify-content: space-between; align-items:center;">
           <span style="font-weight:bold;">MFO-CRM Document Engine</span>
           <button onclick="window.print()" style="background:#4f46e5; color:white; border:none; padding:8px 16px; border-radius:4px; cursor:pointer; font-weight:bold;">Print to PDF</button>
        </div>
        <div class="document-container" style="padding: 40px; background: white;">
            ${replacedHtml}
            
            <div style="margin-top: 60px; border-top: 2px solid #e2e8f0; padding-top: 20px; font-size: 0.85em; color: #64748b; text-align: center;">
               CONFIDENTIAL DOCUMENT — Generated by MFO-CRM Billing Engine at ${new Date().toLocaleString()}
            </div>
        </div>
        
        <script>
            // Optionally auto-print
            // window.onafterprint = function() { window.close(); }
            // setTimeout(() => window.print(), 500);
        </script>
    </body>
    </html>
    `;

    return htmlShell;
}
